name: Publish

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v3

      - name: Setup
        uses: ./.github/actions/setup-node-environment

      - name: Publish package
        run: npx jsr publish
